apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: ops
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
      version: v1.4.0
  template:
    metadata:
      labels:
        k8s-app: node-exporter
        version: v1.4.0
    spec:
      containers:
        - name: prometheus-node-exporter
          image: "alexcld/node-exporter-port-9910:v.1.4.0"
          #imagePullPolicy: "Always"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/rootfs
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|boot|run)($|/)
          ports:
            - name: metrics
              containerPort: 9910
              hostPort: 9910
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          #resources:
          #  limits:
          #    cpu: 10m
          #    memory: 50Mi
          #  requests:
          #    cpu: 10m
          #    memory: 50Mi
      hostNetwork: true
      hostPID: true
      hostIPC: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /rootfs
        - name: dev
          hostPath:
            path: /dev
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: ops
  annotations:
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9910
      protocol: TCP
      targetPort: 9910
  selector:
    k8s-app: node-exporter
