模板：

{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
{{if eq $v.status "resolved"}}
## [Prometheus恢复信息]({{$v.generatorURL}})
#### [{{$v.labels.alertname}}]({{$var}})
###### <font color="#02b340">告警集群</font>：{{$v.labels.k8scluster}}
###### <font color="#02b340">告警级别</font>：{{$v.labels.severity}}
###### <font color="#02b340">开始时间</font>：{{GetCSTtime $v.startsAt}}
###### <font color="#02b340">结束时间</font>：{{GetCSTtime $v.endsAt}}
###### <font color="#02b340">故障主机IP</font>：{{$v.labels.instance}}
##### `Annotations：`{{$v.annotations.summary}}
![Prometheus](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
{{else}}
## [Prometheus告警信息]({{$v.generatorURL}})
#### [{{$v.labels.alertname}}]({{$var}})
###### <font color="#FF0000">告警集群</font>：{{$v.labels.k8scluster}}
###### <font color="#FF0000">告警级别</font>：{{$v.labels.severity}}
###### <font color="#FF0000">开始时间</font>：{{GetCSTtime $v.startsAt}}
###### <font color="#FF0000">故障主机IP</font>：{{$v.labels.instance}}
##### `Annotations：`{{$v.annotations.summary}}
![Prometheus](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
{{end}}
{{ end }}


json:

{
    "receiver": "default",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "labels": {
                "alertname": "PodCPUUsage-warning",
                "k8scluster": "test1-k8s",
                "namespace": "kubesphere-logging-system",
                "pod": "elasticsearch-logging-data-0",
                "severity": "warning"
            },
            "annotations": {
                "summary": "命名空间: kubesphere-logging-system | Pod名称: elasticsearch-logging-data-0 CPU使用大于65% (当前值: 71.38808918954389)"
            },
            "startsAt": "2021-10-28T06:40:29.193Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "http://prometheus-5b9498dbc6-xb9kk:9090/graph?g0.expr=sum+by%28pod%2C+namespace%2C+k8scluster%29+%28rate%28container_cpu_usage_seconds_total%7Bimage%21%3D%22%22%2Ck8scluster%3D%22test1-k8s%22%7D%5B5m%5D%29+%2A+100%29+%3E+65\u0026g0.tab=1",
            "fingerprint": "af81b1bfa25d1baf"
        }
    ],
    "groupLabels": {},
    "commonLabels": {
        "alertname": "PodCPUUsage-warning",
        "k8scluster": "test1-k8s",
        "namespace": "kubesphere-logging-system",
        "pod": "elasticsearch-logging-data-0",
        "severity": "warning"
    },
    "commonAnnotations": {
        "summary": "命名空间: kubesphere-logging-system | Pod名称: elasticsearch-logging-data-0 CPU使用大于65% (当前值: 71.38808918954389)"
    },
    "externalURL": "http://alertmanager.china.com",
    "version": "4",
    "groupKey": "{}:{}",
    "truncatedAlerts": 0
}
